### ISSUE TITLE
[bug] Косяк!

### ISSUE THREAD

**Issue by dmsob** [GrVl-dev/GrVl-dev.github.io#1]
Можно и тут писать баги ) только я почему-то не могу ставить метки (( добавь меня к репе

**Comment by GrVl-dev** [comment]
Добавил в репу

**Comment by dmsob** [comment]
<img width="796" alt="image" src="https://github.com/GrVl-dev/GrVl-dev.github.io/assets/45265592/e8fbe8a0-799b-43fa-a595-07a4065317a4">
сам ты коллаборатор )))
