### ISSUE TITLE
Главная страница. Предложение

### ISSUE THREAD

**Issue by GrVl-dev** [GrVl-dev/GrVl-dev.github.io#16]
![2024-04-25_13-20-29](https://github.com/GrVl-dev/GrVl-dev.github.io/assets/51849015/c7133dcb-7690-473a-a26f-7568ce1ecab7)

**Comment by dmsob** [comment]
Причем вверху именно акции(надо будет категории новостей мутить в БД), а переход на Новости и там всё подряд, но текущие акции(актуальные) самые первые
