### ISSUE TITLE
Форма обратной связи на странице Контакты

### ISSUE THREAD

**Issue by dmsob** [GrVl-dev/GrVl-dev.github.io#3]
<img width="939" alt="image" src="https://github.com/GrVl-dev/GrVl-dev.github.io/assets/45265592/8b28b48c-41c8-4b71-8da8-8ab7b883898d">
Надо примерно такую, т.е. Имя, Мыло, Текст, "Отправить", а не телефон... Она просто нормально там смотреться будет, а то сейчас как-то "висит" в центре 2 поля ))

**Comment by GrVl-dev** [comment]
Сделано
