### ISSUE TITLE
Кнопка Контакты

### ISSUE THREAD

**Issue by dmsob** [GrVl-dev/GrVl-dev.github.io#4]
<img width="154" alt="image" src="https://github.com/GrVl-dev/GrVl-dev.github.io/assets/45265592/8d956795-52c1-4b6c-b484-6848c1e15860">
А надо ли её выделять как кнопку? это же пункт меню у нас теперь, ну т.е. изначально задумка то в том, что по её нажатию не страница открывается, а модальное окно с формой выскакивает, а у нас не так и смысла как-то отделять её от остального меню нету...

**Comment by GrVl-dev** [comment]
Пока может так оставим, она там в принципе смотрится
