### ISSUE TITLE
Калькулятор

### ISSUE THREAD

**Issue by dmsob** [GrVl-dev/GrVl-dev.github.io#7]
<img width="37" alt="image" src="https://github.com/GrVl-dev/GrVl-dev.github.io/assets/45265592/0e2f3465-8bfc-42e5-9726-c358e36f1b7b">
Углы мне кажется лучше прямые сделать, без скруглений

**Comment by dmsob** [comment]
Тут же закину
![image](https://github.com/GrVl-dev/GrVl-dev.github.io/assets/45265592/915b944d-f273-42c9-ba14-dd8c08fdd1fc)

**Comment by GrVl-dev** [comment]
хуясе, если в коммите указывать номер проблемы, она тут подхватывается сразу. Прикольно
